name: Heroku build and deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd quasar_site/
        yarn
        yarn ssrbuild
    - name: deploy
      run: |
        cd quasar_site/dist/ssr/
        git init
        git config user.email "morteza@mcneel.com"
        git config user.name "Morteza Karimi"
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/mcneel-apidocs.git
        git add .
        git commit -m "CI build"
        git push heroku master --force

    - name: invalidate cache
      run: |
        curl --location 'https://api.mcneel.com/cloudfront/invalidate' --header 'Authorization: Basic ${{ secrets.BOZO_API_KEY }}' --header 'Content-Type: application/json' --data '{"url":"https://developer.rhino3d.com/api/*"}'

