name: Heroku build and deploy

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install and build
      run: |
        cd quasar_site/
        yarn
        yarn ssrbuild

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls
    - name: init git repo and deploy
      run: |
        cd quasar_site/dist/ssr
        git init
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/mcneel-apidocs.git
        git push heroku master --force
